services:
  postgres:
    container_name: postgres
    image: postgres:latest
    command: -c max_connections=100
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=local"
      - "POSTGRES_PASSWORD=local"
      - "POSTGRES_DB=local"
    networks:
      - local
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/db.sql

  keycloak:
    container_name: keycloak
    build: keycloak
    depends_on:
      - postgres
    networks:
      - local
    ports:
      - "18080:8080" # Changed from 8080 to 18080
      - "18443:8443" # Changed from 8443 to 18443
      - "5005:5005"
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      DEBUG: "true"
      DEBUG_PORT: "*:5005"

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    command: >
      - "--requirepass redis"
    networks:
      - local

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    networks:
      - local
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://localhost:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

  wiremock:
    container_name: wiremock
    image: wiremock/wiremock:latest
    ports:
      - "8081:8080"
    volumes:
      - ./wiremock:/home/wiremock/mappings
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]

networks:
  local:
    name: local
