services:

  nodejs:
    container_name: nodejs
    image: node:lts
    working_dir: /app
    volumes:
      - ./nodejs:/app
    command: sh -c "npm init -y && npm install && node index.js"
    ports:
      - "3000:3000"
    networks:
      - local

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    ports:
      - "18082:80"
    environment:
      - "PGADMIN_DEFAULT_EMAIL=user@local.email"
      - "PGADMIN_DEFAULT_PASSWORD=local"
    networks:
      - local

  postgres:
    container_name: postgres
    image: postgres:latest
    command: -c max_connections=100
    ports:
      - "15432:5432"
    environment:
      - "POSTGRES_USER=local"
      - "POSTGRES_PASSWORD=local"
      - "POSTGRES_DB=local"
    networks:
      - local
    volumes:
      - ./postgres/data:/var/lib/postgresql
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/db.sql

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    depends_on:
      - postgres
    networks:
      - local
    ports:
      - "18080:8080" # Changed from 8080 to 18080
      - "18443:8443" # Changed from 8443 to 18443
      - "15005:5005"
#    extra_hosts:
#      - host.docker.internal:host-gateway
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: POSTGRESQL
      DB_ADDR: postgres
      DB_PORT: 15432
      DB_DATABASE: local
      DB_USER: keycloak
      DB_PASSWORD: keycloak
      DEBUG: "true"
      DEBUG_PORT: "*:5005"
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start-dev"]
#    entrypoint: ["/opt/keycloak/bin/kc.sh", "start", "--verbose"]

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "16379:6379"
    command: >
      - "--requirepass redis"
    networks:
      - local

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - "MONGO_INITDB_ROOT_USERNAME=local"
      - "MONGO_INITDB_ROOT_PASSWORD=local"
      - "MONGO_INITDB_DATABASE=local"
    networks:
      - local
    volumes:
      - ./mongodb/data:/data/db

  kafka-ui:
    container_name: kafka_ui
    image: kafbat/kafka-ui:latest
    networks:
      - local
    ports:
      - "18083:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:19092

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    networks:
      - local
    ports:
      - "19092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://kafka:19092,EXTERNAL://localhost:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:19092,EXTERNAL://localhost:9092
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

  wiremock:
    container_name: wiremock
    image: wiremock/wiremock:latest
    ports:
      - "18081:8080"
    volumes:
      - ./wiremock:/home/wiremock/mappings
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", "--verbose"]

networks:
  local:
    name: local
