api:
    version: 0.0.1

server:
    port: 8080

spring:
    jpa:
        hibernate:
            ddl-auto: create-drop

        show-sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    datasource:
#        initialize: false # turn off dataSource auto config
        url: jdbc:postgresql://localhost:5432/local?currentSchema=demo
        username: demo
        password: demo
        driver-class-name: org.postgresql.Driver
    application:
        name: demo

security:
    basic:
        enabled: false # turn off basic security auto config

#debug: true
